---
- name: Install kibana
  become: true
  yum:
    name: "/tmp/kibana-{{ elasticsearch_version }}-x86_64.rpm"
    state: present
- name: Start service
  become: true
  systemd:
    name: kibana
    state: started 
    enabled: yes    
  notify: restart kibana
